#helm install supplychain-ca -f values/noproxy-and-novault/ca-server.yaml -n supplychain-net fabric-ca-server
global:
  serviceAccountName: vault-auth
  cluster:
    provider: minikube
    cloudNativeServices: false
  vault:
    type: kubernetes
  proxy:
    provider: none
    externalUrlSuffix: supplychain-net

storage:
  size: 512Mi
server:
  removeCertsOnDelete: true
  tlsStatus: true
  adminUsername: supplychain-admin
  adminPassword: supplychain-adminpw
  subject: "/C=GB/ST=London/L=London/O=Orderer"

# +> IA 
image:
  alpineUtils: jaravan/bevel-alpine:latest
# <+ IA 